### ISSUE TITLE
[Scheduled Maintenance] Downtime guaranteed

### ISSUE THREAD

**Issue by jaiden-04** [iamenews/wiki-uptime#39]

**Comment by jaiden-04** [comment]
Port forwarding settings have to be changed for live testing of new services. This means that the wiki will experience downtime and this downtime may be extensive.

**Comment by iamenews** [comment]
We are still working on the move, and we apologise for the inconvenience caused. For questions related to games, you may visit our [Discord Server](https://discord.gg/hmqCYg4P23) to ask. We will provide more updates on our progress shortly.

**Comment by iamenews** [comment]
We'll try moving another time
